config/routes.rb
Rails.application.routes.draw do
  resources :banners
  root to: 'home#index'

  #Rodas do Dashboard
  get 'chart_pedidos' => 'dashboard#chart_pedidos'
  get 'line_chart_pedidos' => 'dashboard#line_chart_pedidos'
  get 'pie_chart_pedidos' => 'dashboard#pie_chart_pedidos'
  get 'table_pedido_itens' => 'dashboard#table_pedido_itens'
  get 'historico_pedido_itens' => 'dashboard#historico_pedido_itens'
  get 'table_pedido_clientes' => 'dashboard#table_pedido_clientes'
  get 'resumo_pedidos' => 'dashboard#resumo_pedidos'
  get 'call_waiter' => 'dashboard#call_waiter'

  concern :toggleable do
    post 'toggle_habilitado'
  end

  namespace 'users' do
    post 'first-user', action: 'save_first_user', as: 'save_first_user'
    get 'profile', action: 'profile', as: 'profile'
    patch 'profile', action: 'save_profile', as: 'save_profile'
    post 'check-email', action: 'check_email', as: 'check_email'
    post 'check-password', action: 'check_password', as: 'check_password'
    patch ':id/lock', action: 'lock', as: 'lock'
    patch ':id/unlock', action: 'unlock', as: 'unlock'
  end
  resources :categorias, concerns: :toggleable do
    post 'update_posicao'
    resources :subcategorias, concerns: :toggleable do
      post 'update_posicao'
    end
  end
  namespace 'produtos' do
    post 'add-categoria', action: 'add_categoria', as: 'add_categoria'
    get 'new/:subcategory', action: 'new', as: 'new_produto'
  end

  resources :produtos, concerns: :toggleable do
    post 'update_posicao'
    resources :variantes, concerns: :toggleable do
      resources :itens_variantes, concerns: :toggleable
    end
  end

  resources :users
  devise_for :users, path: ''

  resources :categories_books

  namespace 'books' do
    post 'add-category', action: 'add_category', as: 'add_category'
  end
  resources :books

  namespace 'comandas' do
    post 'active', action: 'toggle_active', as: 'active'
    get 'check', action: 'check_comanda', as: 'check'
    get 'check-comanda/:comanda', action: 'check_comanda_action', as: 'check_comanda'
  end
  resources :comandas

  namespace 'api' do
    namespace 'v1' do
      post 'check-comanda', to: 'comandas#check_comanda', as: 'check_comanda'
      post 'link-comanda', to: 'comandas#link_comanda', as: 'link_comanda'
      post 'unlink-comanda', to: 'comandas#unlink_comanda', as: 'unlink_comanda'
      post 'clear-comandas', to: 'comandas#clear_comandas', as: 'clear_comandas'
      post 'auth', to: 'users#authenticate', as: 'auth'
      get 'books/categories', to: 'books#categories', as: 'books_categories'
      post 'books', to: 'books#fetch', as: 'books'
      get 'banners', to: 'banners#fetch', as: 'banners'

      get 'cardapio', to: 'cardapio#index', as: 'cardapio_index'
      post 'cardapio/produtos/:subcategorias_id',
           to: 'cardapio#fetch', as: 'cardapio_produtos'
      get 'call-waiter/:table', to: 'cardapio#call_waiter', as: 'call-waiter'

      post 'orders', to: 'pedido#orders', as: 'orders'
      post 'pedido', to: 'pedido#create', as: 'pedido'

      #Tables
      get 'table/link/:number', to: 'table#link', as: 'link'
      get 'table/unlink/:number', to: 'table#unlink', as: 'unlink'

      #Checkout
      post 'checkout/ordersby_comanda',
           to: 'checkout#ordersby_comanda', as: 'ordersby_comanda'
      post 'checkout/pedir_conta', to: 'checkout#pedir_conta', as: 'pedir_conta'
      post 'checkout/print', to: 'checkout#print', as: 'print'

      post 'events', to: 'events#fetch'
    end
  end

  scope 'cardapio' do
    scope 'categories' do
      get '', to: 'cardapio#fetch_categories'
      post '', to: 'cardapio#add_category'
      put '', to: 'cardapio#update_category'
      delete ':id', to: 'cardapio#delete_category'
      post 'reorder', to: 'cardapio#reorder_categories'
      post 'toggle', to: 'cardapio#toggle_category'
    end

    scope 'subcategories' do
      post '', to: 'cardapio#add_subcategory'
      put '', to: 'cardapio#update_subcategory'
      delete ':id', to: 'cardapio#delete_subcategory'
      post 'reorder', to: 'cardapio#reorder_subcategories'
      post 'toggle', to: 'cardapio#toggle_subcategory'
    end

    scope 'products' do
      get ':subcategory', to: 'cardapio#fetch_produtos'
      post 'reorder', to: 'cardapio#reorder_products'
      post 'toggle', to: 'cardapio#toggle_product'
    end

    scope 'variants' do
      post 'reorder', to: 'cardapio#reorder_variants'
      post 'toggle', to: 'cardapio#toggle_variant'
      post '', to: 'cardapio#create_variant'
      put '', to: 'cardapio#update_variant'
      delete ':product/:id', to: 'cardapio#delete_variant'
    end

    scope 'variants_items' do
      post 'reorder', to: 'cardapio#reorder_variants_items'
      post 'toggle', to: 'cardapio#toggle_variant_item'
      post '', to: 'cardapio#create_variant_item'
      put '', to: 'cardapio#update_variant_item'
      delete ':product/:variant/:id', to: 'cardapio#delete_variant_item'
    end
  end
  resources :cardapio
  resources :tables
  resources :events

  scope 'orders' do
    post 'by-date', to: 'orders#orders_by_date', as: 'orders_by_date'
  end
  resources :orders

  scope 'balcony' do
    get '', to: 'balcony#index', as: 'balcony'
    get 'orders', to: 'balcony#fetch_orders', as: 'balcony_orders'
    post 'order', to: 'balcony#update_order', as: 'update_order'
    get 'finalized', to: 'balcony#finalized', as: 'balcony_finalized'
    get 'fetch-finalized', to: 'balcony#fetch_finalized', as: 'fetch_finalized'
    get 'checkout', to: 'balcony#checkout', as: 'balcony_checkout'
    get 'fetch-checkout', to: 'balcony#fetch_checkout', as: 'fetch_checkout'
    get 'fetch-checkout-waiting',
        to: 'balcony#fetch_checkout_waiting', as: 'fetch_checkout_waiting'
    post 'close-table', to: 'balcony#close_table', as: 'close_table'
    post 'close-comanda', to: 'balcony#close_comanda', as: 'close_comanda'
    post 'print', to: 'balcony#print', as: 'print'
    put 'products-update', to: 'balcony#products_update'
    delete 'order-product/:order/:product',
           to: 'balcony#delete_order_product', as: 'delete_order_product'
  end

  scope 'print_logs' do
    get '', to: 'print_logs#fetch'
    post '', to: 'print_logs#create'
  end

  resources :company_data

  post 'waiter-calls', to: 'home#waiter_calls'
end

app/models/banner.rb
class Banner
  include Mongoid::Document

  paginates_per 8

  field :texto, type: String
  mount_uploader :imagem, BannerImageUploader
  field :data_inicio, type: Date
  field :data_fim, type: Date
  belongs_to :produto, optional: true
  belongs_to :event, optional: true

  def as_json(options)
    super.as_json(options).merge({ full_imagem: full_imagem, produto: produto, event: event })
  end

  def data_inicio_human
    self.data_inicio ? self.data_inicio.strftime('%d/%m/%Y') : nil
  end

  def data_fim_human
    self.data_fim ? self.data_fim.strftime('%d/%m/%Y') : nil
  end

  def full_imagem
    "#{$request.protocol}#{$request.host_with_port}#{self.imagem}"
  end
end

app/controllers/api/v1/banners_controller.rb
class Api::V1::BannersController < ActionController::Base
  skip_before_action :verify_authenticity_token

  def fetch
    $request = request

    banners =
      Banner.any_of(
        { :data_inicio.lte => Date.today, :data_fim.gte => Date.today },
        { data_inicio: nil, data_fim: nil }
      )

    render json: banners
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_banner, only: %i[show edit update destroy]

  # GET /banners
  # GET /banners.json
  def index
    @page_title = 'Banners'
    @banners = Banner.order(texto: :asc).page(params[:page])

    @banners = @banners.where(texto: /.*#{params[:q]}.*/i) if !params[:q].blank?
  end

  # GET /banners/1
  # GET /banners/1.json
  def show; end

  # GET /banners/new
  def new
    @page_title = 'Novo Banner'
    @banner = Banner.new
    @products = Produto.order_by(nome: :asc)
    @events = Event.order_by(data_inicio: :desc)
  end

  # GET /banners/1/edit
  def edit
    @page_title = 'Editar Banner'
    @products = Produto.order_by(nome: :asc)
    @events = Event.order_by(data_inicio: :desc)
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    if (params[:banner_association_choice] == 'product')
      @banner.unset(:event_id)
    end

    if (params[:banner_association_choice] == 'event')
      @banner.unset(:produto_id)
    end

    @banner.save validate: false

    redirect_to banners_path, notice: 'Banner salvo com sucesso'
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    @banner.update(banner_params)

    if (params[:banner_association_choice] == 'product')
      @banner.unset(:event_id)
    end

    if (params[:banner_association_choice] == 'event')
      @banner.unset(:produto_id)
    end

    @banner.save validate: false

    redirect_to banners_path, notice: 'Banner salvo com sucesso'
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html do
        redirect_to banners_url, notice: 'Banner excluído com sucesso'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_banner
    @banner = Banner.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def banner_params
    params.require(:banner).permit(
      :texto,
      :imagem,
      :data_inicio,
      :data_fim,
      :produto_id,
      :event_id
    )
  end
end

app/helpers/banners_helper.rb
module BannersHelper; end

app/views/banners/_form.html.erb
<%= form_for @banner, html: { id: 'banner-form' } do |f| %>
  <% if !@banner.new_record? %>
    <%= f.hidden_field :id %>
  <% end %>

  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= f.label :texto, 'Texto' %>
        <%= f.text_field :texto, class: 'form-control' %>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :imagem, 'Imagem' %>
            <%= f.file_field :imagem, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-3">
          <%= f.label :data_inicio, 'Início' %>
          <%= f.text_field :data_inicio, class: 'form-control datepicker', value: @banner.data_inicio_human %>
        </div>

        <div class="col-md-3">
          <%= f.label :data_fim, 'Fim' %>
          <%= f.text_field :data_fim, class: 'form-control datepicker', value: @banner.data_fim_human %>
        </div>
      </div>
    </div>
  </div>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Associar banner</h3>
        </div>

        <div class="card-body">
            <div class="my-2">
                <div class="form-check form-check-inline">
                    <%
                    checked = ''

                    if @banner.new_record?
                        checked = 'checked'
                    else
                        if @banner.produto_id
                            checked = 'checked'
                        end
                    end
                    %>

                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="banner_association_choice" 
                        id="banner_association_choice_product" 
                        value="product"
                        <%= checked %>
                    >
                    <label class="form-check-label" for="banner_association_choice_product">Produto</label>
                </div>

                <div class="form-check form-check-inline">
                    <%
                    checked = ''

                    if @banner.event_id
                        checked = 'checked'
                    end
                    %>

                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="banner_association_choice" 
                        id="banner_association_choice_event" 
                        value="event"
                        <%= checked %>
                    >
                    <label class="form-check-label" for="banner_association_choice_event">Evento</label>
                </div>
            </div>

            <div class="row" id="product-select-container">
                <div class="col-md-6">  
                    <div class="form-group">
                        <%= f.label :produto, 'Produto' %>
                        <%= f.collection_select :produto_id, @products, :id, :nome, { include_blank: true }, { class: 'form-control select-2' } %>
                    </div>
                </div>
            </div>

            <div class="row" id="event-select-container">
                <div class="col-md-6">  
                    <div class="form-group">
                        <%= f.label :event, 'Evento' %>
                        <%= f.collection_select :event_id, @events, :id, :nome, { include_blank: true }, { class: 'form-control select-2' } %>
                    </div>
                </div>
            </div>
        </div>
    </div>

  <button type="submit" class="btn btn-success btn-lg"><i class="fa fa-check"></i> Salvar</button>
<% end %>

app/views/banners/edit.html.erb
<%= render 'form', banner: @banner %>

app/views/banners/index.html.erb
<div class="row my-2">
    <div class="col-md-6">
      <% if policy(:banner).create? %>
        <a href="<%= new_banner_path %>" class="btn btn-primary"><i class="fa fa-plus"></i> Novo Banner</a>
      <% end %>
    </div>

    <div class="col-md-6 text-right">
      <%= form_tag '', method: :get do %>
        <div class="input-group">
          <%= text_field_tag 'q', params[:q], class: 'form-control', placeholder: 'Buscar' %>
          
          <div class="input-group-append">
            <button class="btn btn-primary" type="button"><i class="fa fa-search"></i></button>
          </div>
        </div>
      <% end %>
    </div>
</div>

<% if !@banners.empty? %>
  <div class="row" id="banners-list">
    <% @banners.each do |b| %>
      <div class="col-md-3 mb-3">
        <div class="card h-100">
          <img src="<%= b.imagem %>" class="card-img-top">

          <div class="card-body">
            <p class="card-text"><%= b.texto %></p>

            <% if b.data_inicio %>
              <p class="card-text"><small><%= b.data_inicio_human %> a <%= b.data_fim_human %></small></p>
            <% end %>

            <% if b.produto %>
              <div class="product">
                <img src="<%= b.produto.imagem %>">

                <p><%= b.produto.nome %></p>
              </div>
            <% end %>
            
            <% if b.event %>
              <div class="product">
                <img src="<%= b.event.imagem %>">

                <p><%= b.event.nome %></p>
              </div>
            <% end %>
          </div>

          <div class="card-footer text-right">
            <% if policy(b).edit? %>
              <a href="<%= edit_banner_path(b) %>" class="btn btn-sm btn-primary"><i class="fa fa-pencil-alt"></i> Editar</a>
            <% end %>

            <% if policy(b).destroy? %>
              <%= link_to banner_path(b), method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse Banner?' }, class: 'btn btn-danger btn-sm' do %>
                <i class="fa fa-trash"></i> Excluir
              <%end%>
            <%end%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
    <div class="empty-data-container">
        <%= image_tag 'picture.png' %>

        <p>Nenhum banner encontrado</p>
    </div>
<% end %>

<%= render 'paginators/default', model: @banners %>

app/views/banners/new.html.erb
<%= render 'form', banner: @banner %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>