config/routes.rb
Rails.application.routes.draw do
  resources :banners
  root to: 'home#index'

  #Rodas do Dashboard
  get 'chart_pedidos' => 'dashboard#chart_pedidos'
  get 'line_chart_pedidos' => 'dashboard#line_chart_pedidos'
  get 'pie_chart_pedidos' => 'dashboard#pie_chart_pedidos'
  get 'table_pedido_itens' => 'dashboard#table_pedido_itens'
  get 'historico_pedido_itens' => 'dashboard#historico_pedido_itens'
  get 'table_pedido_clientes' => 'dashboard#table_pedido_clientes'
  get 'resumo_pedidos' => 'dashboard#resumo_pedidos'
  get 'call_waiter' => 'dashboard#call_waiter'

  concern :toggleable do
    post 'toggle_habilitado'
  end

  namespace 'users' do
    post 'first-user', action: 'save_first_user', as: 'save_first_user'
    get 'profile', action: 'profile', as: 'profile'
    patch 'profile', action: 'save_profile', as: 'save_profile'
    post 'check-email', action: 'check_email', as: 'check_email'
    post 'check-password', action: 'check_password', as: 'check_password'
    patch ':id/lock', action: 'lock', as: 'lock'
    patch ':id/unlock', action: 'unlock', as: 'unlock'
  end
  resources :categorias, concerns: :toggleable do
    post 'update_posicao'
    resources :subcategorias, concerns: :toggleable do
      post 'update_posicao'
    end
  end
  namespace 'produtos' do
    post 'add-categoria', action: 'add_categoria', as: 'add_categoria'
    get 'new/:subcategory', action: 'new', as: 'new_produto'
  end

  resources :produtos, concerns: :toggleable do
    post 'update_posicao'
    resources :variantes, concerns: :toggleable do
      resources :itens_variantes, concerns: :toggleable
    end
  end

  resources :users
  devise_for :users, path: ''

  resources :categories_books

  namespace 'books' do
    post 'add-category', action: 'add_category', as: 'add_category'
  end
  resources :books

  namespace 'comandas' do
    post 'active', action: 'toggle_active', as: 'active'
    get 'check', action: 'check_comanda', as: 'check'
    get 'check-comanda/:comanda', action: 'check_comanda_action', as: 'check_comanda'
  end
  resources :comandas

  namespace 'api' do
    namespace 'v1' do
      post 'check-comanda', to: 'comandas#check_comanda', as: 'check_comanda'
      post 'link-comanda', to: 'comandas#link_comanda', as: 'link_comanda'
      post 'unlink-comanda', to: 'comandas#unlink_comanda', as: 'unlink_comanda'
      post 'clear-comandas', to: 'comandas#clear_comandas', as: 'clear_comandas'
      post 'auth', to: 'users#authenticate', as: 'auth'
      get 'books/categories', to: 'books#categories', as: 'books_categories'
      post 'books', to: 'books#fetch', as: 'books'
      get 'banners', to: 'banners#fetch', as: 'banners'

      get 'cardapio', to: 'cardapio#index', as: 'cardapio_index'
      post 'cardapio/produtos/:subcategorias_id',
           to: 'cardapio#fetch', as: 'cardapio_produtos'
      get 'call-waiter/:table', to: 'cardapio#call_waiter', as: 'call-waiter'

      post 'orders', to: 'pedido#orders', as: 'orders'
      post 'pedido', to: 'pedido#create', as: 'pedido'

      #Tables
      get 'table/link/:number', to: 'table#link', as: 'link'
      get 'table/unlink/:number', to: 'table#unlink', as: 'unlink'

      #Checkout
      post 'checkout/ordersby_comanda',
           to: 'checkout#ordersby_comanda', as: 'ordersby_comanda'
      post 'checkout/pedir_conta', to: 'checkout#pedir_conta', as: 'pedir_conta'
      post 'checkout/print', to: 'checkout#print', as: 'print'

      post 'events', to: 'events#fetch'
    end
  end

  scope 'cardapio' do
    scope 'categories' do
      get '', to: 'cardapio#fetch_categories'
      post '', to: 'cardapio#add_category'
      put '', to: 'cardapio#update_category'
      delete ':id', to: 'cardapio#delete_category'
      post 'reorder', to: 'cardapio#reorder_categories'
      post 'toggle', to: 'cardapio#toggle_category'
    end

    scope 'subcategories' do
      post '', to: 'cardapio#add_subcategory'
      put '', to: 'cardapio#update_subcategory'
      delete ':id', to: 'cardapio#delete_subcategory'
      post 'reorder', to: 'cardapio#reorder_subcategories'
      post 'toggle', to: 'cardapio#toggle_subcategory'
    end

    scope 'products' do
      get ':subcategory', to: 'cardapio#fetch_produtos'
      post 'reorder', to: 'cardapio#reorder_products'
      post 'toggle', to: 'cardapio#toggle_product'
    end

    scope 'variants' do
      post 'reorder', to: 'cardapio#reorder_variants'
      post 'toggle', to: 'cardapio#toggle_variant'
      post '', to: 'cardapio#create_variant'
      put '', to: 'cardapio#update_variant'
      delete ':product/:id', to: 'cardapio#delete_variant'
    end

    scope 'variants_items' do
      post 'reorder', to: 'cardapio#reorder_variants_items'
      post 'toggle', to: 'cardapio#toggle_variant_item'
      post '', to: 'cardapio#create_variant_item'
      put '', to: 'cardapio#update_variant_item'
      delete ':product/:variant/:id', to: 'cardapio#delete_variant_item'
    end
  end
  resources :cardapio
  resources :tables
  resources :events

  scope 'orders' do
    post 'by-date', to: 'orders#orders_by_date', as: 'orders_by_date'
  end
  resources :orders

  scope 'balcony' do
    get '', to: 'balcony#index', as: 'balcony'
    get 'orders', to: 'balcony#fetch_orders', as: 'balcony_orders'
    post 'order', to: 'balcony#update_order', as: 'update_order'
    get 'finalized', to: 'balcony#finalized', as: 'balcony_finalized'
    get 'fetch-finalized', to: 'balcony#fetch_finalized', as: 'fetch_finalized'
    get 'checkout', to: 'balcony#checkout', as: 'balcony_checkout'
    get 'fetch-checkout', to: 'balcony#fetch_checkout', as: 'fetch_checkout'
    get 'fetch-checkout-waiting',
        to: 'balcony#fetch_checkout_waiting', as: 'fetch_checkout_waiting'
    post 'close-table', to: 'balcony#close_table', as: 'close_table'
    post 'close-comanda', to: 'balcony#close_comanda', as: 'close_comanda'
    post 'print', to: 'balcony#print', as: 'print'
    put 'products-update', to: 'balcony#products_update'
    delete 'order-product/:order/:product',
           to: 'balcony#delete_order_product', as: 'delete_order_product'
  end

  scope 'print_logs' do
    get '', to: 'print_logs#fetch'
    post '', to: 'print_logs#create'
  end

  resources :company_data

  post 'waiter-calls', to: 'home#waiter_calls'
end

app/models/user.rb
class User
  include Mongoid::Document

  extend Enumerize

  enumerize :role, in: %i[admin common kitchen balcony], default: :common

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  ## Database authenticatable
  field :nome, type: String, default: ''
  field :email, type: String, default: ''
  field :role
  field :locked, type: Boolean, default: false
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token, type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def active_for_authentication?
    super && !locked?
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ActionController::Base
  skip_before_action :verify_authenticity_token

  def authenticate
    user = User.where(email: params[:email])

    if user.exists?
      if user.first.valid_password?(params[:password])
        if can_change_settings?(user.first)
          render json: { error: false }
        else
          render json: {
                   error: true, message: 'Este usuário não possui permissão'
                 }
        end
      else
        render json: { error: true, message: 'Senha inválida' }
      end
    else
      render json: { error: true, message: 'Usuário inválido' }
    end
  end

  def can_change_settings?(user)
    user.role.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[save_first_user]
  before_action :set_user, only: %i[show edit update destroy lock unlock]

  def save_first_user
    user = User.new(user_params)

    user.role = :admin

    redirect_to root_path if sign_in user if user.save validate: false
  end

  def profile
    @page_title = 'Perfil'
    @user = current_user
  end

  def save_profile
    user = current_user

    user.update user_params

    if not params['user']['new_password'].blank?
      user.password = params['user']['new_password']
      user.save validate: false
    end

    redirect_to users_profile_path, notice: 'Perfil salvo com sucesso'
  end

  def index
    @page_title = 'Usuários'
    @users = User.all
  end

  def create
    # byebug

    @user = User.new user_params

    # @user.role = user_params2["role"].to_i

    # respond_to do |format|
    #     if user.save validate: false
    #         #redirect_to usuarios_path
    #         format.html { redirect_to user, notice: 'Usuario cadastrado com sucesso' }
    #         format.json { head :no_content }
    #     end
    # end

    @user.save validate: false

    redirect_to users_path, notice: 'Usuário salvo com sucesso'
  end

  def update
    @user.update user_params

    # @user.role = user_params2["role"].to_i

    @user.save validate: false

    redirect_to users_path, notice: 'Usuário salvo com sucesso'
  end

  def new
    @page_title = 'Usuários <small>Novo</small>'
    @user = User.new
  end

  def edit
    @page_title = 'Usuários <small>Editar</small>'
  end

  def lock
    @user.locked = true
    @user.save validate: false

    redirect_to users_path, notice: 'Usuário bloqueado com sucesso'
  end

  def unlock
    @user.locked = false
    @user.save validate: false

    redirect_to users_path, notice: 'Usuário desbloqueado com sucesso'
  end

  def check_email
    email = params['user']['email']

    if params['_action'] == 'update'
      user = User.find(params['_id'])

      if user.email == email
        render json: true
      else
        render json: User.where(email: email).first.nil?
      end
    end

    if params['_action'] == 'insert'
      render json: User.where(email: email).first.nil?
    end
  end

  def check_password
    render json:
             User.find(params['_id']).valid_password?(
               params['user']['old_password']
             )
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_path, notice: 'Usuario removido com sucesso'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit :id, :nome, :email, :password, :role
  end
end

app/helpers/user_helper.rb
module UserHelper; end

app/views/users/_form.html.erb
<%= form_for @user, html: { id: 'user-form' } do |f| %>

<%= f.hidden_field :id %>
<%= hidden_field_tag :insert_mode, @user.new_record? %>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Dados do Usuário</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <%= f.label :nome, 'Nome' %>
                    <%= f.text_field :nome, class: 'form-control', autofocus: true %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <%= f.label :email, 'Email' %>
                    <%= f.text_field :email, class: 'form-control' %>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <%= f.label :role, 'Perfil' %>
                    <%= f.select :role, User.role.options, {}, {class: 'form-control'} %>
                </div>
            </div>
        </div>

        <% if @user.new_record? %>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <%= f.label :password, 'Senha' %>
                        <%= f.password_field :password, class: 'form-control' %>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <%= f.label :confirm_password, 'Repita a senha' %>
                        <%= f.password_field :confirm_password, class: 'form-control' %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<% if not @user.new_record? %>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Trocar senha <small>Deixe em branco se não quiser trocar</small></h3>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <%= f.label :password, 'Nova senha' %>
                        <%= f.password_field :password, class: 'form-control' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

<button type="submit" class="btn btn-success btn-lg mb-3"><i class="fa fa-check"></i> Salvar</button>

<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="my-2">
    <% if policy(:user).create? %>
        <a href="<%= new_user_path %>" class="btn btn-primary"><i class="fa fa-plus"></i> Novo Usuário</a>
    <% end %>
</div>

<div class="card">
    <div class="card-body">
        <table class="table table-hover" id="users-list">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Perfil</th>
                    <th data-orderable="false"></th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |u| %>
                    <%
                    rowClass = ''

                    if u.locked?
                        rowClass = 'text-muted'
                    end
                    %>
                    <tr class="<%= rowClass %>">
                        <td><%= u.nome %></td>
                        <td><%= u.email %></td>
                        <td><%= u.role_text %></td>
                        <td>
                            <div class="table-actions">
                                <% if policy(u).edit? %>
                                    <a href="<%= edit_user_path u %>" class="btn btn-primary btn-sm"><i class="fa fa-pencil-alt"></i> Editar</a>
                                <%end%>

                                <% if u.locked? %>
                                    <% if policy(u).block? %>
                                        <%= link_to users_unlock_path(u), method: :patch, data: { confirm: 'Tem certeza que deseja desbloquear esse usuário?' }, class: 'btn btn-secondary btn-sm' do %>
                                            <i class="fa fa-lock-open"></i> Desbloquear
                                        <%end%>
                                    <%end%>
                                <% else %>
                                    <% if policy(u).unblock? %>
                                        <%= link_to users_lock_path(u), method: :patch, data: { confirm: 'Tem certeza que deseja bloquear esse usuário?' }, class: 'btn btn-secondary btn-sm' do %>
                                            <i class="fa fa-lock"></i> Bloquear
                                        <%end%>
                                    <%end%>
                                <% end %>

                                <% if policy(u).destroy? %>
                                    <%= link_to user_path(u), method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse usuário?' }, class: 'btn btn-danger btn-sm' do %>
                                        <i class="fa fa-trash"></i> Excluir
                                    <%end%>
                                <%end%>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/profile.html.erb
<%= form_for @user, url: users_save_profile_path, html: { id: 'profile-form' } do |f| %>

<%= f.hidden_field :id %>

<div class="card">
    <div class="card-body">
        <div class="form-group">
            <%= f.label :nome, 'Nome' %>
            <%= f.text_field :nome, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :email, 'E-mail' %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Trocar senha <small class="text-muted">Deixe em branco se não quiser trocar</small></h3>
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <%= f.label :old_password, 'Senha atual' %>
                    <%= f.password_field :old_password, class: 'form-control' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <%= f.label :new_password, 'Nova senha' %>
                    <%= f.password_field :new_password, class: 'form-control' %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <%= f.label :confirm_new_password, 'Repita a nova senha' %>
                    <%= f.password_field :confirm_new_password, class: 'form-control' %>
                </div>
            </div>
        </div>
    </div>
</div>

<button type="submit" class="btn btn-success btn-lg mb-3"><i class="fa fa-check"></i> Salvar</button>

<% end %>