config/routes.rb
Rails.application.routes.draw do
  resources :banners
  root to: 'home#index'

  #Rodas do Dashboard
  get 'chart_pedidos' => 'dashboard#chart_pedidos'
  get 'line_chart_pedidos' => 'dashboard#line_chart_pedidos'
  get 'pie_chart_pedidos' => 'dashboard#pie_chart_pedidos'
  get 'table_pedido_itens' => 'dashboard#table_pedido_itens'
  get 'historico_pedido_itens' => 'dashboard#historico_pedido_itens'
  get 'table_pedido_clientes' => 'dashboard#table_pedido_clientes'
  get 'resumo_pedidos' => 'dashboard#resumo_pedidos'
  get 'call_waiter' => 'dashboard#call_waiter'

  concern :toggleable do
    post 'toggle_habilitado'
  end

  namespace 'users' do
    post 'first-user', action: 'save_first_user', as: 'save_first_user'
    get 'profile', action: 'profile', as: 'profile'
    patch 'profile', action: 'save_profile', as: 'save_profile'
    post 'check-email', action: 'check_email', as: 'check_email'
    post 'check-password', action: 'check_password', as: 'check_password'
    patch ':id/lock', action: 'lock', as: 'lock'
    patch ':id/unlock', action: 'unlock', as: 'unlock'
  end
  resources :categorias, concerns: :toggleable do
    post 'update_posicao'
    resources :subcategorias, concerns: :toggleable do
      post 'update_posicao'
    end
  end
  namespace 'produtos' do
    post 'add-categoria', action: 'add_categoria', as: 'add_categoria'
    get 'new/:subcategory', action: 'new', as: 'new_produto'
  end

  resources :produtos, concerns: :toggleable do
    post 'update_posicao'
    resources :variantes, concerns: :toggleable do
      resources :itens_variantes, concerns: :toggleable
    end
  end

  resources :users
  devise_for :users, path: ''

  resources :categories_books

  namespace 'books' do
    post 'add-category', action: 'add_category', as: 'add_category'
  end
  resources :books

  namespace 'comandas' do
    post 'active', action: 'toggle_active', as: 'active'
    get 'check', action: 'check_comanda', as: 'check'
    get 'check-comanda/:comanda', action: 'check_comanda_action', as: 'check_comanda'
  end
  resources :comandas

  namespace 'api' do
    namespace 'v1' do
      post 'check-comanda', to: 'comandas#check_comanda', as: 'check_comanda'
      post 'link-comanda', to: 'comandas#link_comanda', as: 'link_comanda'
      post 'unlink-comanda', to: 'comandas#unlink_comanda', as: 'unlink_comanda'
      post 'clear-comandas', to: 'comandas#clear_comandas', as: 'clear_comandas'
      post 'auth', to: 'users#authenticate', as: 'auth'
      get 'books/categories', to: 'books#categories', as: 'books_categories'
      post 'books', to: 'books#fetch', as: 'books'
      get 'banners', to: 'banners#fetch', as: 'banners'

      get 'cardapio', to: 'cardapio#index', as: 'cardapio_index'
      post 'cardapio/produtos/:subcategorias_id',
           to: 'cardapio#fetch', as: 'cardapio_produtos'
      get 'call-waiter/:table', to: 'cardapio#call_waiter', as: 'call-waiter'

      post 'orders', to: 'pedido#orders', as: 'orders'
      post 'pedido', to: 'pedido#create', as: 'pedido'

      #Tables
      get 'table/link/:number', to: 'table#link', as: 'link'
      get 'table/unlink/:number', to: 'table#unlink', as: 'unlink'

      #Checkout
      post 'checkout/ordersby_comanda',
           to: 'checkout#ordersby_comanda', as: 'ordersby_comanda'
      post 'checkout/pedir_conta', to: 'checkout#pedir_conta', as: 'pedir_conta'
      post 'checkout/print', to: 'checkout#print', as: 'print'

      post 'events', to: 'events#fetch'
    end
  end

  scope 'cardapio' do
    scope 'categories' do
      get '', to: 'cardapio#fetch_categories'
      post '', to: 'cardapio#add_category'
      put '', to: 'cardapio#update_category'
      delete ':id', to: 'cardapio#delete_category'
      post 'reorder', to: 'cardapio#reorder_categories'
      post 'toggle', to: 'cardapio#toggle_category'
    end

    scope 'subcategories' do
      post '', to: 'cardapio#add_subcategory'
      put '', to: 'cardapio#update_subcategory'
      delete ':id', to: 'cardapio#delete_subcategory'
      post 'reorder', to: 'cardapio#reorder_subcategories'
      post 'toggle', to: 'cardapio#toggle_subcategory'
    end

    scope 'products' do
      get ':subcategory', to: 'cardapio#fetch_produtos'
      post 'reorder', to: 'cardapio#reorder_products'
      post 'toggle', to: 'cardapio#toggle_product'
    end

    scope 'variants' do
      post 'reorder', to: 'cardapio#reorder_variants'
      post 'toggle', to: 'cardapio#toggle_variant'
      post '', to: 'cardapio#create_variant'
      put '', to: 'cardapio#update_variant'
      delete ':product/:id', to: 'cardapio#delete_variant'
    end

    scope 'variants_items' do
      post 'reorder', to: 'cardapio#reorder_variants_items'
      post 'toggle', to: 'cardapio#toggle_variant_item'
      post '', to: 'cardapio#create_variant_item'
      put '', to: 'cardapio#update_variant_item'
      delete ':product/:variant/:id', to: 'cardapio#delete_variant_item'
    end
  end
  resources :cardapio
  resources :tables
  resources :events

  scope 'orders' do
    post 'by-date', to: 'orders#orders_by_date', as: 'orders_by_date'
  end
  resources :orders

  scope 'balcony' do
    get '', to: 'balcony#index', as: 'balcony'
    get 'orders', to: 'balcony#fetch_orders', as: 'balcony_orders'
    post 'order', to: 'balcony#update_order', as: 'update_order'
    get 'finalized', to: 'balcony#finalized', as: 'balcony_finalized'
    get 'fetch-finalized', to: 'balcony#fetch_finalized', as: 'fetch_finalized'
    get 'checkout', to: 'balcony#checkout', as: 'balcony_checkout'
    get 'fetch-checkout', to: 'balcony#fetch_checkout', as: 'fetch_checkout'
    get 'fetch-checkout-waiting',
        to: 'balcony#fetch_checkout_waiting', as: 'fetch_checkout_waiting'
    post 'close-table', to: 'balcony#close_table', as: 'close_table'
    post 'close-comanda', to: 'balcony#close_comanda', as: 'close_comanda'
    post 'print', to: 'balcony#print', as: 'print'
    put 'products-update', to: 'balcony#products_update'
    delete 'order-product/:order/:product',
           to: 'balcony#delete_order_product', as: 'delete_order_product'
  end

  scope 'print_logs' do
    get '', to: 'print_logs#fetch'
    post '', to: 'print_logs#create'
  end

  resources :company_data

  post 'waiter-calls', to: 'home#waiter_calls'
end

app/models/variante.rb
class Variante
  include Mongoid::Document
  include Mongoid::Paranoia
  include Toggleable

  field :nome, type: String
  field :tipo, type: String
  field :habilitado, type: Boolean, default: true
  field :maxSelect, type: Integer
  field :posicao, type: Integer, default: 0
  embedded_in :pedido
  embeds_many :itens_variante

  default_scope -> { order_by(posicao: :asc) }

  def as_json(options = nil)
    super.as_json(options).merge({ tipo_text: tipo_text })
  end

  def tipo_text
    self.tipo == true ? 'Múltipla escolha' : 'Única escolha'
  end
end

app/controllers/variantes_controller.rb
class VariantesController < ApplicationController
  before_action :set_produto, only: %i[index new edit update create destroy]
  before_action :set_variante, only: %i[show edit update destroy]

  # GET /variantes
  # GET /variantes.json
  def index
    @page_title = @produto.nome + ' <small>Variantes</small>'
    @variantes = @produto.variantes.all
  end

  # GET /variantes/1
  # GET /variantes/1.json
  def show; end

  # GET /variantes/new
  def new
    @page_title = @produto.nome + ' <small>Nova Variante</small>'
    @variante = @produto.variantes.new
  end

  # GET /variantes/1/edit
  def edit
    @page_title = @produto.nome + ' <small>Editar Variante</small>'
  end

  # POST /variantes
  # POST /variantes.json
  def create
    @variante = @produto.variantes.new(variante_params)

    respond_to do |format|
      if @variante.save
        format.html do
          redirect_to produto_variantes_path(@produto),
                      notice: 'Variante criada com sucesso.'
        end
        format.json { render :show, status: :created, location: @variante }
      else
        format.html { render :new }
        format.json do
          render json: @variante.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /variantes/1
  # PATCH/PUT /variantes/1.json
  def update
    respond_to do |format|
      if @variante.update(variante_params)
        format.html do
          redirect_to produto_variantes_path(@produto),
                      notice: 'Variante atualizada com sucesso.'
        end
        format.json { render :show, status: :ok, location: @variante }
      else
        format.html { render :edit }
        format.json do
          render json: @variante.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /variantes/1
  # DELETE /variantes/1.json
  def destroy
    @variante.destroy
    respond_to do |format|
      format.html do
        redirect_to produto_variantes_path(@produto),
                    notice: 'Variante removida com sucesso.'
      end
      format.json { head :no_content }
    end
  end

  def toggle_habilitado
    @variante.toggle_habilitado

    if @variante.save
      render nothing: true
    else
      render nothing: true, status: :unprocessable_entity
    end
  end

  #Habilitar e desabilitar produto
  def toggle_habilitado
    #byebug
    @produto = Produto.find(params[:produto_id])
    @variante = @produto.variantes.find(params[:variante_id])
    @variante.toggle_habilitado

    if @variante.save
      head :ok
    else
      head :ok, status: :unprocessable_entity
    end
  end

  private

  def set_produto
    @produto = Produto.find(params[:produto_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_variante
    @variante = @produto.variantes.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def variante_params
    params.require(:variante).permit(:nome, :tipo, :maxSelect)
  end
end

app/views/variantes/_form.html.erb
<%= form_for([@produto, @variante], html: { id: "variante" }) do |f| %>

    <% if @variante.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@variante.errors.count, "error") %> prohibited this variante from being saved:</h2>

        <ul>
        <% @variante.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <%= f.label :nome, 'Nome da Variante' %>
                        <%= f.text_field :nome, class: 'form-control', autofocus: true %>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <%= f.label :tipo, 'Tipo Seleção' %> <br>
                        <div class="custom-control custom-radio">
                            <%= f.radio_button :tipo, true, :checked => true, :id => "customRadio1", :class => 'custom-control-input' %>
                            <label class="custom-control-label" for="customRadio1">Múltiplas</label>
                        </div>
                        <div class="custom-control custom-radio">
                            <%= f.radio_button :tipo, false, :id => "customRadio2", :class => 'custom-control-input' %>
                            <label class="custom-control-label" for="customRadio2">Única</label>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <%= f.label :maxSelect, 'Máximo de Seleções' %>
                        <%= f.number_field :maxSelect, min: 1, class: "required form-control", value: "1" %>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-success btn-lg mb-3"><i class="fa fa-check"></i> Salvar</button>

<% end %>

app/views/variantes/edit.html.erb
<%= render 'form', produto: @produto %>

app/views/variantes/index.html.erb
<div class="row my-2">
    <div class="col-md-6">
        <% if policy(:produto).create? %>
            <a href="<%= new_produto_variante_path %>" class="btn btn-primary"><i class="fa fa-plus"></i> Nova Variante</a>
        <% end %>
    </div>
</div>
<% if !@variantes.empty? %>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <div class="table-responsive">
          <table id="variantes-list" class="table table-hover table-sm">
            <thead>
              <tr>
                <td>
                  Variante
                </td>
                <td>
                  Tipo de Seleção
                </td>
                <td>
                  
                </td>
              </tr>
            </thead>
            <tbody>
              <% @variantes.each do |variante| %>
                <tr>
                  <td>
                    <%= variante.nome%>
                  </td>
                  <td>
                    <%= variante.tipo == "true" ? "Múltipla" : "Única"%>
                  </td>
                  <td class="text-right">
                    <% if policy(@produto).edit? %>
                      <%= link_to produto_variante_itens_variantes_path(@produto, variante), class: 'btn btn-secondary btn-sm' do %>
                        <i class="fa fa-align-justify"></i> Itens
                      <%end%>
                      <%= link_to edit_produto_variante_path(@produto,variante), class: 'btn btn-primary btn-sm' do %>
                        <i class="fa fa-pencil-alt"></i> Editar
                      <%end%>
                    <% end %>
                    <% if policy(@produto).destroy? %>
                      <%= link_to produto_variante_path(@produto, variante), method: :delete, data: { confirm: 'Tem certeza que deseja remover?' }, class: 'btn btn-danger btn-sm' do %>
                        <i class="fa fa-trash"></i> Excluir
                      <%end%>
                    <%end%>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
    <div class="empty-data-container">
        <i class="fas fa-align-justify fa-9x"></i>
        <p>Nenhuma variante encontrado</p>
    </div>
<% end %>

app/views/variantes/new.html.erb
<%= render 'form', produto: @produto %>