config/routes.rb
Rails.application.routes.draw do
  resources :banners
  root to: 'home#index'

  #Rodas do Dashboard
  get 'chart_pedidos' => 'dashboard#chart_pedidos'
  get 'line_chart_pedidos' => 'dashboard#line_chart_pedidos'
  get 'pie_chart_pedidos' => 'dashboard#pie_chart_pedidos'
  get 'table_pedido_itens' => 'dashboard#table_pedido_itens'
  get 'historico_pedido_itens' => 'dashboard#historico_pedido_itens'
  get 'table_pedido_clientes' => 'dashboard#table_pedido_clientes'
  get 'resumo_pedidos' => 'dashboard#resumo_pedidos'
  get 'call_waiter' => 'dashboard#call_waiter'

  concern :toggleable do
    post 'toggle_habilitado'
  end

  namespace 'users' do
    post 'first-user', action: 'save_first_user', as: 'save_first_user'
    get 'profile', action: 'profile', as: 'profile'
    patch 'profile', action: 'save_profile', as: 'save_profile'
    post 'check-email', action: 'check_email', as: 'check_email'
    post 'check-password', action: 'check_password', as: 'check_password'
    patch ':id/lock', action: 'lock', as: 'lock'
    patch ':id/unlock', action: 'unlock', as: 'unlock'
  end
  resources :categorias, concerns: :toggleable do
    post 'update_posicao'
    resources :subcategorias, concerns: :toggleable do
      post 'update_posicao'
    end
  end
  namespace 'produtos' do
    post 'add-categoria', action: 'add_categoria', as: 'add_categoria'
    get 'new/:subcategory', action: 'new', as: 'new_produto'
  end

  resources :produtos, concerns: :toggleable do
    post 'update_posicao'
    resources :variantes, concerns: :toggleable do
      resources :itens_variantes, concerns: :toggleable
    end
  end

  resources :users
  devise_for :users, path: ''

  resources :categories_books

  namespace 'books' do
    post 'add-category', action: 'add_category', as: 'add_category'
  end
  resources :books

  namespace 'comandas' do
    post 'active', action: 'toggle_active', as: 'active'
    get 'check', action: 'check_comanda', as: 'check'
    get 'check-comanda/:comanda', action: 'check_comanda_action', as: 'check_comanda'
  end
  resources :comandas

  namespace 'api' do
    namespace 'v1' do
      post 'check-comanda', to: 'comandas#check_comanda', as: 'check_comanda'
      post 'link-comanda', to: 'comandas#link_comanda', as: 'link_comanda'
      post 'unlink-comanda', to: 'comandas#unlink_comanda', as: 'unlink_comanda'
      post 'clear-comandas', to: 'comandas#clear_comandas', as: 'clear_comandas'
      post 'auth', to: 'users#authenticate', as: 'auth'
      get 'books/categories', to: 'books#categories', as: 'books_categories'
      post 'books', to: 'books#fetch', as: 'books'
      get 'banners', to: 'banners#fetch', as: 'banners'

      get 'cardapio', to: 'cardapio#index', as: 'cardapio_index'
      post 'cardapio/produtos/:subcategorias_id',
           to: 'cardapio#fetch', as: 'cardapio_produtos'
      get 'call-waiter/:table', to: 'cardapio#call_waiter', as: 'call-waiter'

      post 'orders', to: 'pedido#orders', as: 'orders'
      post 'pedido', to: 'pedido#create', as: 'pedido'

      #Tables
      get 'table/link/:number', to: 'table#link', as: 'link'
      get 'table/unlink/:number', to: 'table#unlink', as: 'unlink'

      #Checkout
      post 'checkout/ordersby_comanda',
           to: 'checkout#ordersby_comanda', as: 'ordersby_comanda'
      post 'checkout/pedir_conta', to: 'checkout#pedir_conta', as: 'pedir_conta'
      post 'checkout/print', to: 'checkout#print', as: 'print'

      post 'events', to: 'events#fetch'
    end
  end

  scope 'cardapio' do
    scope 'categories' do
      get '', to: 'cardapio#fetch_categories'
      post '', to: 'cardapio#add_category'
      put '', to: 'cardapio#update_category'
      delete ':id', to: 'cardapio#delete_category'
      post 'reorder', to: 'cardapio#reorder_categories'
      post 'toggle', to: 'cardapio#toggle_category'
    end

    scope 'subcategories' do
      post '', to: 'cardapio#add_subcategory'
      put '', to: 'cardapio#update_subcategory'
      delete ':id', to: 'cardapio#delete_subcategory'
      post 'reorder', to: 'cardapio#reorder_subcategories'
      post 'toggle', to: 'cardapio#toggle_subcategory'
    end

    scope 'products' do
      get ':subcategory', to: 'cardapio#fetch_produtos'
      post 'reorder', to: 'cardapio#reorder_products'
      post 'toggle', to: 'cardapio#toggle_product'
    end

    scope 'variants' do
      post 'reorder', to: 'cardapio#reorder_variants'
      post 'toggle', to: 'cardapio#toggle_variant'
      post '', to: 'cardapio#create_variant'
      put '', to: 'cardapio#update_variant'
      delete ':product/:id', to: 'cardapio#delete_variant'
    end

    scope 'variants_items' do
      post 'reorder', to: 'cardapio#reorder_variants_items'
      post 'toggle', to: 'cardapio#toggle_variant_item'
      post '', to: 'cardapio#create_variant_item'
      put '', to: 'cardapio#update_variant_item'
      delete ':product/:variant/:id', to: 'cardapio#delete_variant_item'
    end
  end
  resources :cardapio
  resources :tables
  resources :events

  scope 'orders' do
    post 'by-date', to: 'orders#orders_by_date', as: 'orders_by_date'
  end
  resources :orders

  scope 'balcony' do
    get '', to: 'balcony#index', as: 'balcony'
    get 'orders', to: 'balcony#fetch_orders', as: 'balcony_orders'
    post 'order', to: 'balcony#update_order', as: 'update_order'
    get 'finalized', to: 'balcony#finalized', as: 'balcony_finalized'
    get 'fetch-finalized', to: 'balcony#fetch_finalized', as: 'fetch_finalized'
    get 'checkout', to: 'balcony#checkout', as: 'balcony_checkout'
    get 'fetch-checkout', to: 'balcony#fetch_checkout', as: 'fetch_checkout'
    get 'fetch-checkout-waiting',
        to: 'balcony#fetch_checkout_waiting', as: 'fetch_checkout_waiting'
    post 'close-table', to: 'balcony#close_table', as: 'close_table'
    post 'close-comanda', to: 'balcony#close_comanda', as: 'close_comanda'
    post 'print', to: 'balcony#print', as: 'print'
    put 'products-update', to: 'balcony#products_update'
    delete 'order-product/:order/:product',
           to: 'balcony#delete_order_product', as: 'delete_order_product'
  end

  scope 'print_logs' do
    get '', to: 'print_logs#fetch'
    post '', to: 'print_logs#create'
  end

  resources :company_data

  post 'waiter-calls', to: 'home#waiter_calls'
end

app/models/produto.rb
class Produto
  include Mongoid::Document
  include Mongoid::Paranoia
  include Toggleable
  include ActionView::Helpers::NumberHelper

  extend Enumerize

  enumerize :tipo, in: %i[balcao cozinha], default: :balcao

  field :nome, type: String
  field :posicao, type: Integer, default: 0
  field :descricao, type: String
  field :valor_promocional, type: Float
  field :valor_final, type: Float
  field :tipo
  field :habilitado, type: Boolean, default: true

  mount_uploader :imagem, PictureUploader
  mount_uploader :gif, GifUploader

  #default_scope -> { where(habilitado: true) }
  #scope :habilidados -> { where(habilitado: true) }

  validates :nome, presence: true

  # validates :descricao,
  #   presence: true

  validates :valor_promocional, presence: true, numericality: true

  validates :valor_final,
            presence: true,
            numericality: {
              greater_than_or_equal_to: :valor_promocional,
              message: 'não pode ser menor que o valor promocional'
            }

  belongs_to :subcategorias
  embeds_many :variantes

  def as_json(options = nil)
    super.as_json(options).merge(
      { full_imagem: full_imagem, full_gif: full_gif }
    )
  end

  def full_imagem
    "#{$request.protocol}#{$request.host_with_port}#{self.imagem}"
  end

  def full_gif
    if !self.gif.blank?
      "#{$request.protocol}#{$request.host_with_port}#{self.gif}"
    else
      nil
    end
  end

  default_scope -> { order_by(posicao: :asc) }

  # before_create do |document|
  #   subcategoria = Subcategoria.find(document.subcategorias_id)
  #   if posicao_maior = subcategoria.produtos.max('posicao')
  #     document.posicao = posicao_maior + 1
  #   else
  #     document.posicao = 0
  #   end
  # end

  # after_destroy do |document|
  #   Produto.gt(posicao: document.posicao).inc(posicao: -1)
  # end

  # before_save do |document|
  #   if document.posicao_changed?
  #     reorder_produtos(document.posicao, document.posicao_was,document.subcategorias_id)
  #   end
  # end

  def reorder_produtos(new_position, old_position, subcategorias_id)
    #byebug
    subcategoria = Subcategoria.find(subcategorias_id)
    if new_position < 0 || new_position > subcategoria.produtos.max('posicao')
      raise 'Invalid position value'
    end

    if (new_position > old_position)
      Produto.gt(posicao: old_position).lte(posicao: new_position).inc(
        posicao: -1
      )
    else
      Produto.gte(posicao: new_position).lt(posicao: old_position).inc(
        posicao: 1
      )
    end
  end

  def valor_final_text
    number_to_currency self.valor_final,
                       separator: ',', delimiter: '.', unit: ''
  end

  def valor_promocional_text
    number_to_currency self.valor_promocional,
                       separator: ',', delimiter: '.', unit: ''
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[show edit update destroy]

  skip_before_action :verify_authenticity_token, only: %i[destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @page_title = 'Produtos'
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show; end

  # GET /produtos/new
  def new
    @page_title = 'Produto <small>Novo</small>'
    @produto = Produto.new
    @produto.subcategorias_id = params[:subcategory]
  end

  # GET /produtos/1/edit
  def edit
    @page_title = 'Produto <small>Editar</small>'
  end

  # POST /produtos
  # POST /produtos.json
  def create
    products =
      Produto.where(subcategorias_id: params[:produto][:subcategorias_id])
        .order_by(posicao: :asc)

    products.each do |p|
      p.posicao = p.posicao + 1
      p.save validate: false
    end

    @produto = Produto.new produto_params

    @produto.valor_final = parse_currency params[:produto][:valor_final]
    @produto.valor_promocional =
      parse_currency params[:produto][:valor_promocional]

    @produto.save validate: false

    redirect_to cardapio_index_path, notice: 'Produto salvo com sucesso.'
  end

  def parse_currency(value)
    value.gsub('.', '').gsub(',', '.').to_f
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    @produto.update produto_params

    @produto.valor_final = parse_currency params[:produto][:valor_final]
    @produto.valor_promocional =
      parse_currency params[:produto][:valor_promocional]

    @produto.save validate: false

    redirect_to cardapio_index_path, notice: 'Produto salvo com sucesso.'
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    # respond_to do |format|
    #     format.html { redirect_to produtos_url, notice: 'Produto removido com sucesso.' }
    #     format.json { head :no_content }
    # end
  end

  #Habilitar e desabilitar produto
  def toggle_habilitado
    @produto = Produto.find(params[:produto_id])
    @produto.toggle_habilitado

    if @produto.save
      head :ok
    else
      head :ok, status: :unprocessable_entity
    end
  end

  def add_categoria
    categoria = Categoria.new params.permit(:nome)
    categoria.save
    render json: categoria
  end

  #Ajustar posicao da categoria
  def update_posicao
    @produto = Produto.find(params[:produto_id])
    @produto.posicao = params[:posicao]

    if @produto.save
      head :ok
    else
      head :ok, status: :unprocessable_entity
    end
  end

  private

  def set_categoria
    #@categoria = Categoria.find(params[:categoria_id])
    #@categoria = Categoria.find(params[:produto][:categoria_id])
    @categoria = @subcategoria.categoria_id
  end

  def set_subcategoria
    if params[:produto].nil?
      @subcategoria = Subcategoria.find(@produto.subcategorias.id)
      #byebug
    else
      @subcategoria = Subcategoria.find(params[:produto][:subcategoria])
      #byebug
    end
  end

  def set_produto
    @produto = Produto.find(params[:id])
    #byebug
  end

  def produto_params
    params.require(:produto).permit(
      :nome,
      :descricao,
      :valor_promocional,
      :valor_final,
      :imagem,
      :gif,
      :tipo,
      :subcategorias_id
    )
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper; end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true, html: { id: "produto-form" }) do |f| %>

<% if !@produto.new_record? %>
    <%= f.hidden_field :id %>
<% end %>

<%= f.hidden_field :subcategorias_id %>

<div class="card">
    <div class="card-body">
        <div class="form-group">
            <%= f.label :nome, 'Nome' %>
            <%= f.text_field :nome, class: 'form-control', autofocus: true %>
        </div>

        <div class="form-group">
            <%= f.label :descricao, 'Descrição' %>
            <%= f.text_area :descricao, class: 'form-control', rows: 5 %>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <%= f.label :tipo, 'Saída' %>
                    <%= f.select :tipo, Produto.tipo.options, {}, {class: 'form-control'} %>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <%= f.label :valor_final, 'Valor' %>
                    <%= f.text_field :valor_final, class: "form-control", value: @produto.valor_final_text %>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <%= f.label :valor_promocional, 'Valor Promocional' %>
                    <%= f.text_field :valor_promocional, class: "form-control", value: @produto.valor_promocional_text %>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <%= f.label :imagem, 'Imagem' %>
                    <%= f.file_field :imagem, class: 'form-control' %>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <%= f.label :gif, 'GIF' %>
                    <%= f.file_field :gif, class: 'form-control' %>
                </div>
            </div>
        </div>
    </div>
</div>

<button type="submit" class="btn btn-success btn-lg mb-3"><i class="fa fa-check"></i> Salvar</button>

<% end %>

app/views/produtos/edit.html.erb
<%= render 'form', produto: @produto %>

app/views/produtos/index.html.erb
<div class="row my-2">
    <div class="col-md-6">
        <% if policy(:produto).create? %>
            <a href="<%= new_produto_path %>" class="btn btn-primary"><i class="fa fa-plus"></i> Novo Produto</a>
        <% end %>
    </div>
</div>
<% if !@produtos.empty? %>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <div class="table-responsive">
          <table id="produtos-list" class="table table-hover table-sm">
            <thead>
              <tr>
                <td>Produto</td>
                <td>Subcategoria</td>
                <td></td>
              </tr>
            </thead>
            <tbody>
              <% @produtos.each do |produto| %>
                <tr>
                    <td>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" <%= produto.habilitado==true ? 'checked' : '' %>  data-produto-id="<%= produto.id %>" data-subcategoria-id="<%#= produto.subcategoria.id %>" class="produto-habilitado-toggle custom-control-input" id="<%= produto.id%>">
                            <label class="custom-control-label" for="<%= produto.id%>"><%= produto.nome%></label>
                        </div>
                    </td>
                  <td>
                    <%#= produto.subcategoria.nome%>
                  </td>
                  <td class="text-right">
                    <% if policy(produto).edit? %>
                      <%= link_to produto_variantes_path(produto), class: 'btn btn-secondary btn-sm' do %>
                        <i class="fa fa-align-justify"></i> Variantes
                      <%end%>
                      <%= link_to edit_produto_path(produto), class: 'btn btn-primary btn-sm' do %>
                        <i class="fa fa-pencil-alt"></i> Editar
                      <%end%>
                    <% end %>
                    <% if policy(produto).destroy? %>
                      <%= link_to produto, method: :delete, data: { confirm: 'Tem certeza que deseja remover?' }, class: 'btn btn-danger btn-sm' do %>
                        <i class="fa fa-trash"></i> Excluir
                      <%end%>
                    <%end%>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
    <div class="empty-data-container">
        <i class="fas fa-clipboard-list fa-9x"></i>
        <p>Nenhum produto encontrado</p>
    </div>
<% end %>

app/views/produtos/new.html.erb
<%= render 'form', produto: @produto %>